name: restler-report-parser
services:
  restler-report-parser:
    # image: yukicoder/restler-report-parser:latest
    build: .
    volumes:
      - "./bug_buckets:/app/src/assets/bug_buckets"
      - "./parser_output:/app/dist"
